export { LayerType } from "./LayerType.js"
export { Layer } from "./Layer.js"
export { Data } from "./Data.js"
export { AxisRegistry, AXES } from "./AxisRegistry.js"
export { ColorAxisRegistry } from "./ColorAxisRegistry.js"
export { FilterAxisRegistry, buildFilterGlsl } from "./FilterAxisRegistry.js"
export { Plot } from "./Plot.js"
export { scatterLayerType } from "./ScatterLayer.js"
export { registerLayerType, getLayerType, getRegisteredLayerTypes } from "./LayerTypeRegistry.js"
export { registerAxisQuantityKind, getAxisQuantityKind, getRegisteredAxisQuantityKinds } from "./AxisQuantityKindRegistry.js"
export { registerColorscale, register2DColorscale, getRegisteredColorscales, getRegistered2DColorscales, getColorscaleIndex, get2DColorscaleIndex, buildColorGlsl } from "./ColorscaleRegistry.js"
export { Axis } from "./Axis.js"
export { linkAxes } from "./AxisLink.js"
export { Colorbar } from "./Colorbar.js"
export { colorbarLayerType } from "./ColorbarLayer.js"
export { Colorbar2d } from "./Colorbar2d.js"
export { colorbar2dLayerType } from "./ColorbarLayer2d.js"
export { Float } from "./Float.js"
export { Filterbar } from "./Filterbar.js"
export { filterbarLayerType } from "./FilterbarLayer.js"
export { tileLayerType, TileLayerType } from "./TileLayer.js"
export { registerEpsgDef, parseCrsCode, crsToQkX, crsToQkY, qkToEpsgCode, reproject } from "./EpsgUtils.js"

// Register all matplotlib colorscales (side-effect import)
import "./MatplotlibColorscales.js"
